import {
  Archive,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUUpLeft,
  ArrowUp,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsIn,
  ArrowsLeftRight,
  ArrowsOut,
  Bandaids,
  Barbell,
  Bed,
  BookOpenText,
  Brain,
  CalendarBlank,
  CalendarCheck,
  CalendarDot,
  CalendarDots,
  CalendarPlus,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChatsCircle,
  Check,
  CheckCircle,
  Circle,
  Clock,
  ClockCounterClockwise,
  Compass,
  Confetti,
  Copy,
  CrosshairSimple,
  DotsNine,
  DownloadSimple,
  Drop,
  Fire,
  Flag,
  Flask,
  FloppyDisk,
  Flower,
  FlowerLotus,
  FolderOpen,
  Footprints,
  ForkKnife,
  GearSix,
  Heart,
  Heartbeat,
  ImageBroken,
  ImageSquare,
  Lightbulb,
  Lightning,
  Link,
  List,
  ListBullets,
  ListChecks,
  ListPlus,
  MagnifyingGlass,
  MapTrifold,
  Medal,
  MinusCircle,
  Moon,
  MoonStars,
  MusicNote,
  NotePencil,
  Pause,
  PencilSimple,
  PersonArmsSpread,
  PersonSimpleRun,
  PersonSimpleWalk,
  PiggyBank,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  PushPin,
  Recycle,
  Repeat,
  RocketLaunch,
  Scales,
  Shapes,
  Shield,
  SignOut,
  Smiley,
  Sun,
  Sparkle,
  SpinnerGap,
  SquaresFour,
  Star,
  Stop,
  StopCircle,
  Tag,
  Target,
  TextAlignLeft,
  Thermometer,
  Timer,
  Trash,
  Tray,
  TrayArrowDown,
  TrendDown,
  TrendUp,
  UploadSimple,
  UsersThree,
  Warning,
  WarningCircle,
  Wind,
  X,
} from '@phosphor-icons/react'

/**
 * Phosphor icons behind the same `name` API the app has always used.
 *
 * Call sites and the `icon:` fields in lib/*.js still pass Material Symbols
 * names (`monitor_heart`, `self_improvement`, ...). Rather than touch ~250
 * call sites and every data file, this maps each of those names to its
 * Phosphor equivalent in one place. To change an icon, change its entry in
 * MAP below.
 *
 * `fill` swaps the weight to Phosphor's filled variant, which is how active
 * nav items are marked.
 *
 * The glyph is sized in `em` inside a span that carries the `icon` class, so
 * the many CSS rules that size icons via `font-size` (e.g. `.nav-item .icon`)
 * keep working unchanged.
 */
const MAP = {
  accessibility_new: PersonArmsSpread,
  add: Plus,
  add_circle: PlusCircle,
  add_photo_alternate: ImageSquare,
  add_task: ListPlus,
  air: Wind,
  apps: DotsNine,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  auto_awesome: Sparkle,
  auto_stories: BookOpenText,
  bar_chart: ChartBar,
  bedtime: Moon,
  bolt: Lightning,
  broken_image: ImageBroken,
  calendar_month: CalendarBlank,
  category: Shapes,
  celebration: Confetti,
  center_focus_strong: CrosshairSimple,
  check: Check,
  check_circle: CheckCircle,
  checklist: ListChecks,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  circle: Circle,
  close: X,
  close_fullscreen: ArrowsIn,
  content_copy: Copy,
  delete: Trash,
  directions_walk: PersonSimpleWalk,
  diversity_3: UsersThree,
  do_not_disturb_on: MinusCircle,
  done: Check,
  download: DownloadSimple,
  drive_file_move: FolderOpen,
  edit: PencilSimple,
  edit_calendar: CalendarPlus,
  edit_note: NotePencil,
  error: WarningCircle,
  error_outline: WarningCircle,
  event_available: CalendarCheck,
  event_note: CalendarDots,
  exercise: PersonSimpleRun,
  expand_less: CaretUp,
  expand_more: CaretDown,
  explore: Compass,
  favorite: Heart,
  fitness_center: Barbell,
  flag: Flag,
  footprint: Footprints,
  forum: ChatsCircle,
  fullscreen: ArrowsOut,
  fullscreen_exit: ArrowsIn,
  grid_view: SquaresFour,
  healing: Bandaids,
  history: ClockCounterClockwise,
  hotel: Bed,
  inbox: Tray,
  insights: ChartLineUp,
  label: Tag,
  library_add: PlusSquare,
  lightbulb: Lightbulb,
  link: Link,
  list_alt: ListBullets,
  local_fire_department: Fire,
  logout: SignOut,
  light_mode: Sun,
  loop: ArrowsClockwise,
  map: MapTrifold,
  menu: List,
  monitor_heart: Heartbeat,
  monitor_weight: Scales,
  move_to_inbox: TrayArrowDown,
  music_note: MusicNote,
  nights_stay: MoonStars,
  north_east: ArrowUpRight,
  notes: TextAlignLeft,
  open_in_new: ArrowSquareOut,
  pause: Pause,
  play_arrow: Play,
  play_circle: PlayCircle,
  progress_activity: SpinnerGap,
  psychology: Brain,
  push_pin: PushPin,
  query_stats: ChartLine,
  radio_button_unchecked: Circle,
  recycling: Recycle,
  remove_circle_outline: MinusCircle,
  repeat: Repeat,
  restart_alt: ArrowCounterClockwise,
  restaurant: ForkKnife,
  rocket_launch: RocketLaunch,
  save: FloppyDisk,
  savings: PiggyBank,
  schedule: Clock,
  science: Flask,
  search: MagnifyingGlass,
  self_improvement: FlowerLotus,
  sentiment_satisfied: Smiley,
  settings: GearSix,
  shield: Shield,
  show_chart: ChartLine,
  sick: Thermometer,
  south_east: ArrowDownRight,
  spa: Flower,
  star: Star,
  steps: Footprints,
  stop: Stop,
  stop_circle: StopCircle,
  swap_horiz: ArrowsLeftRight,
  sync: ArrowsClockwise,
  target: Target,
  task_alt: CheckCircle,
  timer: Timer,
  today: CalendarDot,
  trending_down: TrendDown,
  trending_flat: ArrowRight,
  trending_up: TrendUp,
  unarchive: Archive,
  undo: ArrowUUpLeft,
  upload_file: UploadSimple,
  warning: Warning,
  water_drop: Drop,
  workspace_premium: Medal,
}

export default function Icon({ name, size = 19, fill = false, className = '', style }) {
  const Glyph = MAP[name]
  if (import.meta.env.DEV && !Glyph) console.warn(`[Icon] no Phosphor mapping for "${name}"`)
  const Cmp = Glyph || Circle
  return (
    <span
      className={`icon${fill ? ' fill' : ''}${className ? ' ' + className : ''}`}
      style={{ fontSize: size, ...style }}
      aria-hidden="true"
    >
      <Cmp size="1em" weight={fill ? 'fill' : 'regular'} />
    </span>
  )
}
